name: first workflow
on: push  # [ push, pull ]
jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: welcome message
              run: |
                echo "My first github actions job"
                ls -altr
                cat README.md
            - name: install cowsay
              run: sudo apt install cowsay
            - name: ascii artwork
              run: cowsay -f dragon "Run for cover" >> dragon.txt
            # - name: list files
            #   run: ls
            # - name: read files
            #   run: cat README.md
              
